config = {
  host: "http://ecc.ideashop.iit.edu:8085",
  transport_options: {
    request: { timeout: 5 }
  },
}

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Persistence.client = Elasticsearch::Client.new(config)