# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b274b69563316a7313716b5757b944028aca5a46bafa27d6c865d7ae9cc2e35fd5bcfdefaf9534735a75d91d2b2b2be577b0aa5e7945f6a5b4e5ddf032fe8e

test:
  secret_key_base: 6d4c2497f0a52475aae80089782d7e549e9b2650d9a5629a959f1543b2fc3996dc910233fc4fc16089bf4dfbbd4a2d416df6e42a010c31915bd38984248d1d96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
